name: Selenium Standalone
version: "1.2.5"
slug: selenium-standalone
description: Selenium Standalone service for Home Assistant add-ons
arch:
  - amd64
url: https://github.com/davida72/selenium-homeassistant
startup: services
boot: auto
ports:
  4444/tcp: 4444
  5900/tcp: 5900
  7900/tcp: 7900
ports_description:
  4444/tcp: Selenium WebDriver API
  5900/tcp: VNC Server (for session viewing)
  7900/tcp: NoVNC Web Interface (browser-based session viewing)
host_network: false
privileged:
  - SYS_ADMIN
apparmor: false
init: false
options:
  Use password to view Selenium sessions: false
schema:
  Use password to view Selenium sessions: bool
